import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import mainImage from '@/assets/images/main_image.jpg'
import styles from '@/styles/Home.module.css'
import {FormEvent, useState} from 'react'
import { Form, Spinner } from 'react-bootstrap'

import Button from 'react-bootstrap/Button';

export default function Home() {

 
const [idea,setcoolname]=useState("")
const [ideaLoading,setcoolnameLoading]=useState(false)
const [ideaLoadingError,setcoolnameError]=useState(false)


async function handleSubmit (e:FormEvent<HTMLFormElement>) {
  e.preventDefault();
  const formdata= new FormData(e.target as HTMLFormElement)
  const prompt= formdata.get("prompt")?.toString().trim()
  if (prompt)
  try {
   setcoolname("")
   setcoolnameError(false)
   setcoolnameLoading(true)
   const response=await fetch("/api/hello?prompt=" + encodeURIComponent(prompt))
   console.log("prompt",encodeURIComponent(prompt))
   const body= await response.json()
   setcoolname(body.idea)

  } catch (error) {
    console.log(error)
    setcoolnameError(false)
    
  }
  finally{
    setcoolnameLoading(false)
  }
}

  return (
    <>
      <Head>
        <title>name your startup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
    <h1>find startup name</h1>
    <h6>powered by openai🔥</h6>
<div className={styles.mainImageContainer}>
<Image
src={mainImage}
fill
alt='a board that says you that you can turn your ideas into reality'
priority
className={styles.mainImage}/>
</div>
<Form action="" onSubmit={handleSubmit} className={styles.inputForm}   >
  
  <Form.Group className='md-3' controlId='prompt-input' >
    <Form.Label>create  a brand name for  .....</Form.Label>
<Form.Control
name='prompt'
placeholder='write clearly of what you want  to build'
maxLength={100}
/>

  </Form.Group>
  <Button type='submit'   className='mb-3'  disabled={ideaLoading}  >
  
  create name
  
  </Button>

  </Form>
  {ideaLoading && <Spinner animation='border'></Spinner>}
  {ideaLoadingError && "something went wrong please try again"}
  {idea && <h5>{idea}</h5>}
      </main>
    </>
  )
}
